@url_dev = http://localhost:3056/v1/api/

## sign up
POST {{url_dev}}shop/signup
Content-Type: application/json

{
    "name" : "HieuMinhVuu",
    "email" : "hieuminhvuu03@gmail.com",
    "password" : "123456"
}